FROM php:8.1-apache
COPY . /var/www/html/
WORKDIR /var/www/html/
EXPOSE 80
RUN \ 
	docker-php-ext-configure pdo_mysql --with-pdo-mysql=mysqlnd \
	&& docker-php-ext-configure mysqli --with-mysqli=mysqlnd \
	&& docker-php-ext-install pdo_mysql \